const GET_ADMINS_PENDING = 'GET_ADMINS_PENDING';
const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS';
const GET_ADMINS_ERROR = 'GET_ADMINS_ERROR';
const DELETE_ADMIN_PENDING = 'DELETE_ADMIN_PENDING';
const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';
const DELETE_ADMIN_ERROR = 'DELETE_ADMIN_ERROR';
const PUT_ADMIN_PENDING = 'PUT_ADMIN_PENDING';
const PUT_ADMIN_SUCCESS = 'PUT_ADMIN_SUCCESS';
const PUT_ADMIN_ERROR = 'PUT_ADMIN_ERROR';
const POST_ADMIN_PENDING = 'POST_ADMIN_PENDING';
const POST_ADMIN_SUCCESS = 'POST_ADMIN_SUCCESS';
const POST_ADMIN_ERROR = 'POST_ADMIN_ERROR';

export {
  GET_ADMINS_PENDING,
  GET_ADMINS_SUCCESS,
  GET_ADMINS_ERROR,
  DELETE_ADMIN_PENDING,
  DELETE_ADMIN_SUCCESS,
  DELETE_ADMIN_ERROR,
  PUT_ADMIN_PENDING,
  PUT_ADMIN_SUCCESS,
  PUT_ADMIN_ERROR,
  POST_ADMIN_PENDING,
  POST_ADMIN_SUCCESS,
  POST_ADMIN_ERROR
};
